### ISSUE TITLE
raise FileNotFoundError(file_path) : I can not convert my tensorflow model .pb to .blob

### ISSUE THREAD

**Issue by Hus174** [luxonis/depthai-docs-website#247]
I tried to convert the file through the online MyriadX Blob converter at http://luxonis.com:8080/ but the server taking too long to respond and the page did not load.
then I follow the blobconverter PyPI package https://pypi.org/project/blobconverter/
when I use the command line to do the Conversion, I got  this  message " ** raise FileNotFoundError(file_path)** "
![1512](https://user-images.githubusercontent.com/88859405/129276767-146757c9-d68d-4307-b003-f84bed1e8637.png)
when I use the Python script, I got the same message 

![gfh](https://user-images.githubusercontent.com/88859405/129277139-6344624e-34e1-4fde-a32e-b9ecb237b400.png)

![gh (1)](https://user-images.githubusercontent.com/88859405/129277144-66607df2-1002-4e92-933b-d0d8d99ea8de.png)

Am I doing something wrong?

**Comment by alex-luxonis** [comment]
Missing space after the file path here, and also between the following arguments:
![image](https://user-images.githubusercontent.com/60824841/129279418-38c185a5-bece-45ae-acbe-6dd2d05891b3.png)


Here you need to prefix with `/`, like `/home/....`, otherwise it's considered a relative path:
![image](https://user-images.githubusercontent.com/60824841/129279194-644eac08-6f80-4ffc-ab10-da2a1dbb3c04.png)

**Comment by Hus174** [comment]
Thank you, Alex, for your reply.  I corrected the file path, and I got the following message

![777777](https://user-images.githubusercontent.com/88859405/129281677-d003a8de-31e7-4faa-8f7c-78a8297ad70f.png)

Does this mean the conversion of the file can not do without the URL request?

**Comment by alex-luxonis** [comment]
So the file reached the server now, but OpenVINO failed to convert the model probably due to bad/unsupported parameters supplied. The entire log printed is relevant here, especially the `stderr` part.

Note: If you copied the tensorflow model conversion snippet from [here](https://github.com/luxonis/blobconverter/blob/dae95d6/cli/README.md#tensorflow-1), you may need to adjust it to your model.
On how to adjust the options, need to read the OpenVINO documentation.

@VanDavv The output displayed as above is very hard to read, as tab/newline whitespaces (`\t`, `\n`) are printed as-is, and not decoded. Maybe we should improve this in blobconverter.

@Hus174 You can make it more readable for now by running your `file.py` script through this helper:
https://gist.github.com/alex-luxonis/dd5e418d62cde4b666c03849c1893609
Copy this `pretty.py` script to the same folder where `file.py` is located, then run:
```
python3 pretty.py file
```
