### ISSUE TITLE
Indicate that OpenVINO Movidius install steps are required

### ISSUE THREAD

**Issue by itsderek23** [luxonis/depthai-docs-website#33]
It's easy for users to miss the Movidius install step when setting up OpenVINO. They aren't using an NCS - they are using DepthAI. We need the same USB rules to function.

![image](https://user-images.githubusercontent.com/7880/76261139-f5c39d00-621e-11ea-9336-16a8d1f91f67.png)

Clarify this in our install steps.

**Comment by Luxonis-Brandon** [comment]
So @itsderek23 yes I'm thinking we should actually spell these steps out in our instructions, as it seems like most users are missing this, since they don't think the neural compute stick has anything to do with us.

For Ubuntu, the on you pasted is recommended.

And for Raspbian, the following is recommended:
![image](https://user-images.githubusercontent.com/32992551/76274140-62ea2900-6245-11ea-9fe4-6a670ba627b5.png)

https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_raspbian.html

So I would imagine we have users install OpenVINO as a step, and then have these spelled out below that step depending on their operating system.

Thoughts?

Thanks,
Brandon

**Comment by alex-luxonis** [comment]
The udev rules installation could be simplified to not necessarily depend on OpenVINO.
Looks like this works:
1. Run this command:
```
echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | sudo tee /etc/udev/rules.d/80-movidius.rules
```
2.  Reset or reconnect(USB) the DepthAI device.

**Comment by alex-luxonis** [comment]
We should also improve the host app and throw a proper error message when the udev rules are not installed (the backend libusb API returns a "permission denied" error in this case).

And in this case potentially offer the user an option to auto-install the rules by running the above script (the user would need to input sudo password).

**Comment by Luxonis-Brandon** [comment]
Totally agreed.  I'll add these to the docs soon.  And just added the proper error message part to the roadmap and made issue for it https://github.com/luxonis/depthai-api/issues/2

**Comment by Luxonis-Brandon** [comment]
So @alex-luxonis I edited the setup instructions to have the udev rules you suggested:
https://docs.luxonis.com/api/#install
